on:
  schedule:
  - cron: "0 10 * * *"

jobs:
 run_script:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@4.2.1
     - name: execute script
       run: bash ./court_gila_he.sh
     
  
